# htop in podman container
#
# podman run --rm -it \
#     --pid host
#     htop
#
FROM alpine:latest
LABEL maintainer "Jeffrey Serio <hyperreal@fedoraproject.org>"

RUN apk --no-cache add htop

CMD [ "htop" ]
